name: Resequence type-1 test
on:
  pull_request:
    branches:
      - project/pp2**
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  resequence-type1-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cdk-erigon
        uses: actions/checkout@v4

      - name: Setup kurtosis for type-1
        uses: ./.github/actions/setup-kurtosis-type1

      - name: Install polycli
        shell: bash
        run: |
          tmp_dir=$(mktemp -d) && curl -L https://github.com/0xPolygon/polygon-cli/releases/download/v0.1.48/polycli_v0.1.48_linux_amd64.tar.gz | tar -xz -C "$tmp_dir" && mv "$tmp_dir"/* /usr/local/bin/polycli && rm -rf "$tmp_dir"
          sudo chmod +x /usr/local/bin/polycli
          /usr/local/bin/polycli version

      - name: Test resequence type-1 PMT
        working-directory: ${{ github.workspace }}
        run: ./.github/scripts/test_resequence.sh

      - name: Prepare logs
        working-directory: ./kurtosis-cdk
        if: failure() && env.ACT != 'true'
        run: |
          mkdir -p ci_logs
          cd ci_logs
          kurtosis service logs cdk-v1 cdk-erigon-rpc-001 --all > cdk-erigon-rpc-001.log
          kurtosis service logs cdk-v1 cdk-erigon-sequencer-001 --all > cdk-erigon-sequencer-001.log
          kurtosis service logs cdk-v1 cdk-node-001 --all > cdk-node-001.log
          kurtosis service logs cdk-v1 zkevm-bridge-service-001 --all > zkevm-bridge-service-001.log

      - name: Upload logs
        if: failure() && env.ACT != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: logs_${{ github.run_id }}
          path: ./kurtosis-cdk/ci_logs
